name: Testing

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: sudo apt-get install -y libsodium-dev

    - name: Build
      run: go build -o .

    - name: Test
      env:
        OWNER: ${{ secrets.TEST_OWNER }}
        REPO: ${{ secrets.TEST_REPO }}
        TOKEN: ${{ secrets.TEST_TOKEN }}
      run: go test -v .

    - name: Test binary
      env:
        TEST_FOO1: ${{ secrets.TEST_FOO1 }}
        TEST_FOO2: ${{ secrets.TEST_FOO2 }}
        TOKEN: ${{ secrets.TEST_TOKEN }}
      run: |
        echo "apply and list"
        echo "TEST_FOO1=$((${TEST_FOO1}+1))" > test.env
        echo "TEST_FOO2=$((${TEST_FOO2}+1))" >> test.env
        ./actions-secrets -owner ${{ secrets.TEST_OWNER }} -repo ${{ secrets.TEST_REPO }} -list test.env -apply test.env -verbose

        echo 1: $((${TEST_FOO1}+1))
        echo 2: $((${TEST_FOO2}+1))
        
        echo "delete and list"
        ./actions-secrets -owner ${{ secrets.TEST_OWNER }} -repo ${{ secrets.TEST_REPO }} -list test.env -delete test.env -verbose
        
        echo "apply again"
        echo "TEST_FOO1=${TEST_FOO1}" > test.env
        echo "TEST_FOO2=${TEST_FOO2}" >> test.env
        ./actions-secrets -owner ${{ secrets.TEST_OWNER }} -repo ${{ secrets.TEST_REPO }} -list test.env -apply test.env -verbose

        echo 1: $((${TEST_FOO1}+1))
        echo 2: $((${TEST_FOO2}+1))
