name: Testing

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Test
      env:
        SECRET_TEST_VAR: ${{ secrets.TEST_VAR }}
      run: |
        echo 1: ${TEST_VAR}
        echo 2: ${SECRET_TEST_VAR}
